version: '3.12'

services:
  django:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      # - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    networks:
      - backend-web

  db:
    image: mysql:8.2.0
    # restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-web

  # react:
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - static-data:/vol/web/static

  # nginx:
  #   image: nginx:latest
  #   build:
  #       context: ./proxy
  #   restart: always
  #   ports:
  #     - 80:8000
  #   volumes:
  #     - static-data:/vol/static
  #   depends_on:
  #       - django
  #       - react

volumes:
  mysql-data:
  static-data:

networks:
  backend-web: